### ISSUE TITLE
Adding other dependencies

### ISSUE THREAD

**Issue by jay-tux** [davidADSP/SIMPLE#21]
Our environment depends on the (external) library `pycatan`, which I tried to install by adding to both the `requirements.txt` and the `Dockerfile`, yet I always get the error that the docker can't find the library:

```
> sudo docker-compose exec app python3 train.py -r -e catan
Logging to logs

Setting up the selfplay training environment opponents...
Traceback (most recent call last):
  File "/app/utils/register.py", line 24, in get_environment
    from catan.envs.catan import CatanEnv
  File "/app/environments/catan/catan/envs/__init__.py", line 1, in <module>
    from catan.envs.catan import CatanEnv
  File "/app/environments/catan/catan/envs/catan.py", line 3, in <module>
    from pycatan import Resource, Coords, Path, Intersection, Hex
ModuleNotFoundError: No module named 'pycatan'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 188, in <module>
    cli()
  File "train.py", line 183, in cli
    main(args)
  File "train.py", line 58, in main
    base_env = get_environment(args.env_name)
  File "/app/utils/register.py", line 32, in get_environment
    raise Exception(f'Install the environment first using: \nbash scripts/install_env.sh {env_name}\nAlso ensure the environment is added to /utils/register.py')
Exception: Install the environment first using: 
bash scripts/install_env.sh catan
Also ensure the environment is added to /utils/register.py
```

However, the environment is in `/utils/register.py`, and the install script has run:
```
> sudo docker-compose exec app pip3 install pycatan        
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pycatan in /home/selfplay/.local/lib/python3.6/site-packages (0.13)
Requirement already satisfied: quotequail in /home/selfplay/.local/lib/python3.6/site-packages (from pycatan) (0.2.3)
```

The setup clearly states that the requirement is satisfied, yet I can't seem to get it loaded?

**Comment by jay-tux** [comment]
Apparently python version mismatch between tf & other library
Closing as unrelated
